[package]
name = "aegisfs-fuzz"
version = "0.1.0"
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
aegisfs = { path = ".." }
libfuzzer-sys = "0.4"
futures = "0.3"
tokio = { version = "1", features = ["rt", "macros"] }

[profile.release]
debug = 1

[[bin]]
name = "chunking_fuzzer"
path = "fuzz_targets/chunking_fuzzer.rs"
test = false
doc = false


[[bin]]
name = "serialization_fuzzer"
path = "fuzz_targets/serialization_fuzzer.rs"
test = false
doc = false

[[bin]]
name = "dedup_fuzzer"
path = "fuzz_targets/dedup_fuzzer.rs"
test = false
doc = false

[[bin]]
name = "compression_fuzzer"
path = "fuzz_targets/compression_fuzzer.rs"
test = false
doc = false
